- name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8
    - name: Run black
      run:
        black --check .
    - name: Run flake8
      run: flake8
